# Combine CSVs From John Hopkins University to 1 Json File (data.json)

In [22]:
import os,pandas as pd,numpy as np, json
dfArray=[]
dates=[]
folderPath="C:\\Users\\I\\Desktop\\covid_multi_line_chart_CSC3007_milestone2\\jhu_csvs"
directory = os.path.join(folderPath)
count=1
for root,dirs,files in os.walk(directory):
    for file in files:
        if (file.endswith(".csv") and count<7):
            df = pd.read_csv(folderPath+"\\"+file)
            try:
                df.drop(columns=df.columns[[0,1,2,4,5,6,9,10,11,12,13]],errors='ignore',axis=1,inplace=True)
            except:
                pass
            df.rename(columns={"Country_Region":"Country"},errors='ignore',inplace=True)
            df.rename(columns={"Country/Region":"Country"},errors='ignore',inplace=True)
            df=df.groupby("Country",as_index=False).sum()
            dates.append(file.split(".")[0])
            dfArray.append(df)
            count+=1

In [23]:
len(dfArray)

6

In [24]:
out={}
for i in range(0,len(dates)):
    out[dates[i]]= dfArray[i].groupby("Country").last().to_dict(orient='index')
with open("data\\country_data.json", "w") as outfile:
    json.dump(out, outfile, indent=4, sort_keys=False)

# Remove countries in country_regions.csv that are not in data.json

In [25]:
import os,pandas as pd,numpy as np, json
filePath="data\\country_regions.csv"

df = pd.read_csv(filePath, encoding='latin-1', sep=",")
df.Region.unique()

array(['Europe', 'Middle east', 'Asia & Pacific', 'South/Latin America',
       'Africa', 'Arab States', 'North America', 'South/Central America'],
      dtype=object)

In [26]:
list(dfArray[1].Country)

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antarctica',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burma',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Diamond Princess',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Holy See',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea, North',
 'Korea, South',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'MS Zaandam',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Summer Olympics 2020',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan*',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'US',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'West Bank and Gaza',
 'Winter Olympics 2022',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [27]:
df.drop(df.index[~df.Country.isin(list(dfArray[1].Country))], inplace=True)
df.drop(df.index[~df.Country.isin(list(dfArray[1].Country))], inplace=True)

In [28]:
dfNew=dfArray[1][~dfArray[1].Country.isin(df.Country.values)]
dfNew

                  Country  Confirmed  Deaths
25                 Brunei      15470      98
28                  Burma     530946   19272
30             Cabo Verde      42463     352
40    Congo (Brazzaville)      20089     367
41       Congo (Kinshasa)      74793    1205
43          Cote d'Ivoire      71815     718
47                Czechia    2480736   36182
49       Diamond Princess        712      13
59               Eswatini      66241    1308
76               Holy See         27       0
82                   Iran    6195403  131639
93           Korea, North          0       0
94           Korea, South     639083    5694
95                 Kosovo     161531    2991
98                   Laos     112083     374
107            MS Zaandam          9       2
118            Micronesia          1       0
119               Moldova     376434   10284
132       North Macedonia     225484    7969
146                Russia   10340011  303496
169  Summer Olympics 2020        865       0
173                 Syria      50310    2901
174               Taiwan*      17050     850
176              Tanzania      29306     737
184                    US   55024198  826342
194    West Bank and Gaza     469748    4919
195  Winter Olympics 2022          0       0

In [29]:
df[df["Country"]=="Afghanistan"]

       Country          Region  Global South
2  Afghanistan  Asia & Pacific  Global South

In [13]:
len(df)

172

In [14]:
array2Add=[
["Brunei","Asia & Pacific"],
["Burma","Asia & Pacific"],
["Cabo Verde","Africa"],
["Congo (Brazzaville)","Africa"],
["Congo (Kinshasa)","Africa"],
["Cote d'Ivoire","Africa"],
["Czechia","Europe"],
["Diamond Princess","United Kingdom"],
["Eswatini","Africa"],
["Holy See","Europe"],
["Iran","Asia & Pacific"],
["Korea, North","Asia & Pacific"],
["Korea, South","Asia & Pacific"],
["Kosovo","Europe"],
["Laos","Asia & Pacific"],
["MS Zaandam","North America"],
["Micronesia","Asia & Pacific"],
["Moldova","Europe"],
["North Macedonia","Europe"],
["Russia","Asia & Pacific"],
["Summer Olympics 2020","Asia & Pacific"],
["Syria","Asia & Pacific"],
["Taiwan*","Asia & Pacific"],
["Tanzania","Africa"],
["US","North America"],
["West Bank and Gaza","Asia & Pacific"],
["Winter Olympics 2022","Asia & Pacific"]
]
len(array2Add)

27

In [15]:
df=df.append(pd.DataFrame(array2Add,columns=["Country","Region"]),ignore_index=True)

C:\Users\I\AppData\Local\Temp\ipykernel_4276\4175388866.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(pd.DataFrame(array2Add,columns=["Country","Region"]),ignore_index=True)

In [16]:
len(df)

199

In [17]:
list(df.groupby("Region"))

[('Africa',
                        Country  Region  Global South
  6                      Angola  Africa  Global South
  16               Burkina Faso  Africa  Global South
  19                    Burundi  Africa  Global South
  20                      Benin  Africa  Global South
  25                   Botswana  Africa  Global South
  29   Central African Republic  Africa  Global South
  32                   Cameroon  Africa  Global South
  47                    Eritrea  Africa  Global South
  49                   Ethiopia  Africa  Global South
  53                      Gabon  Africa  Global South
  57                      Ghana  Africa  Global South
  58                     Gambia  Africa  Global South
  59                     Guinea  Africa  Global South
  60          Equatorial Guinea  Africa  Global South
  63              Guinea-Bissau  Africa  Global South
  79                      Kenya  Africa  Global South
  91                    Liberia  Africa  Global South
  92                    Lesotho  Africa  Global South
  99                 Madagascar  Africa  Global South
  101                      Mali  Africa  Global South
  105                 Mauritius  Africa  Global South
  107                    Malawi  Africa  Global South
  110                Mozambique  Africa  Global South
  111                   Namibia  Africa  Global South
  112                     Niger  Africa  Global South
  113                   Nigeria  Africa  Global South
  131                    Rwanda  Africa  Global South
  134                Seychelles  Africa  Global South
  135               South Sudan  Africa  Global South
  141              Sierra Leone  Africa  Global South
  143                   Senegal  Africa  Global South
  146     Sao Tome and Principe  Africa  Global South
  148                      Chad  Africa  Global South
  149                      Togo  Africa  Global South
  158                    Uganda  Africa  Global South
  168              South Africa  Africa  Global South
  169                    Zambia  Africa  Global South
  171                  Zimbabwe  Africa  Global South
  174                Cabo Verde  Africa           NaN
  175       Congo (Brazzaville)  Africa           NaN
  176          Congo (Kinshasa)  Africa           NaN
  177             Cote d'Ivoire  Africa           NaN
  180                  Eswatini  Africa           NaN
  195                  Tanzania  Africa           NaN),
 ('Arab States',
          Country       Region  Global South
  18      Bahrain  Arab States  Global South
  39     Djibouti  Arab States  Global South
  43      Algeria  Arab States  Global South
  83      Comoros  Arab States  Global South
  97      Morocco  Arab States  Global South
  103  Mauritania  Arab States  Global South
  136       Sudan  Arab States  Global South
  144     Somalia  Arab States  Global South
  152     Tunisia  Arab States  Global South),
 ('Asia & Pacific',
                    Country          Region  Global South
  2             Afghanistan  Asia & Pacific  Global South
  7              Antarctica  Asia & Pacific  Global South
  10              Australia  Asia & Pacific  Global North
  11             Azerbaijan  Asia & Pacific  Global North
  14             Bangladesh  Asia & Pacific  Global South
  24                 Bhutan  Asia & Pacific  Global South
  33                  China  Asia & Pacific  Global South
  51                   Fiji  Asia & Pacific  Global South
  69              Indonesia  Asia & Pacific  Global South
  72                  India  Asia & Pacific  Global South
  78                  Japan  Asia & Pacific  Global North
  80             Kyrgyzstan  Asia & Pacific  Global South
  81               Cambodia  Asia & Pacific  Global South
  82               Kiribati  Asia & Pacific  Global South
  86             Kazakhstan  Asia & Pacific  Global North
  90              Sri Lanka  Asia & Pacific  Global South
  100      Marshall Islands  Asia & Pacific  Global South
  102              Mongolia  Asia & Pacific  Global South
  106              Maldives  Asia & Pacific  Global South
  109              Malaysia  Asia & Pacific  Global South
  117                 Nepal  Asia & Pacific  Global South
  118           New Zealand  Asia & Pacific  Global North
  122      Papua New Guinea  Asia & Pacific  Global South
  123           Philippines  Asia & Pacific  Global South
  124              Pakistan  Asia & Pacific  Global South
  127                 Palau  Asia & Pacific  Global South
  133       Solomon Islands  Asia & Pacific  Global South
  138             Singapore  Asia & Pacific  Global North
  150              Thailand  Asia & Pacific  Global South
  151            Tajikistan  Asia & Pacific  Global South
  153                 Tonga  Asia & Pacific  Global South
  154           Timor-Leste  Asia & Pacific  Global South
  160            Uzbekistan  Asia & Pacific  Global South
  163               Vietnam  Asia & Pacific  Global South
  164               Vanuatu  Asia & Pacific  Global South
  165                 Samoa  Asia & Pacific  Global South
  172                Brunei  Asia & Pacific           NaN
  173                 Burma  Asia & Pacific           NaN
  182                  Iran  Asia & Pacific           NaN
  183          Korea, North  Asia & Pacific           NaN
  184          Korea, South  Asia & Pacific           NaN
  186                  Laos  Asia & Pacific           NaN
  188            Micronesia  Asia & Pacific           NaN
  191                Russia  Asia & Pacific           NaN
  192  Summer Olympics 2020  Asia & Pacific           NaN
  193                 Syria  Asia & Pacific           NaN
  194               Taiwan*  Asia & Pacific           NaN
  197    West Bank and Gaza  Asia & Pacific           NaN
  198  Winter Olympics 2022  Asia & Pacific           NaN),
 ('Europe',
                      Country  Region  Global South
  0                   Andorra  Europe  Global North
  4                   Albania  Europe  Global North
  5                   Armenia  Europe  Global North
  9                   Austria  Europe  Global North
  12   Bosnia and Herzegovina  Europe  Global North
  15                  Belgium  Europe  Global North
  17                 Bulgaria  Europe  Global North
  26                  Belarus  Europe  Global North
  30              Switzerland  Europe  Global North
  37                   Cyprus  Europe  Global North
  38                  Germany  Europe  Global North
  40                  Denmark  Europe  Global North
  45                  Estonia  Europe  Global North
  48                    Spain  Europe  Global North
  50                  Finland  Europe  Global North
  52                   France  Europe  Global North
  54           United Kingdom  Europe  Global North
  56                  Georgia  Europe  Global North
  61                   Greece  Europe  Global North
  66                  Croatia  Europe  Global North
  68                  Hungary  Europe  Global North
  70                  Ireland  Europe  Global North
  74                  Iceland  Europe  Global North
  75                    Italy  Europe  Global North
  89            Liechtenstein  Europe  Global North
  93                Lithuania  Europe  Global North
  94               Luxembourg  Europe  Global North
  95                   Latvia  Europe  Global North
  98                   Monaco  Europe  Global North
  104                   Malta  Europe  Global North
  115             Netherlands  Europe  Global North
  116                  Norway  Europe  Global North
  125                  Poland  Europe  Global North
  126                Portugal  Europe  Global North
  130                 Romania  Europe  Global North
  137                  Sweden  Europe  Global North
  139                Slovenia  Europe  Global North
  140                Slovakia  Europe  Global North
  142              San Marino  Europe  Global North
  155                  Turkey  Europe  Global North
  157                 Ukraine  Europe  Global North
  167                  Serbia  Europe  Global North
  170              Montenegro  Europe  Global North
  178                 Czechia  Europe           NaN
  181                Holy See  Europe           NaN
  185                  Kosovo  Europe           NaN
  189                 Moldova  Europe           NaN
  190         North Macedonia  Europe           NaN),
 ('Middle east',
                    Country       Region  Global South
  1    United Arab Emirates  Middle east  Global South
  46                  Egypt  Middle east  Global South
  71                 Israel  Middle east  Global North
  73                   Iraq  Middle east  Global South
  77                 Jordan  Middle east  Global South
  85                 Kuwait  Middle east  Global South
  87                Lebanon  Middle east  Global South
  96                  Libya  Middle east  Global South
  119                  Oman  Middle east  Global South
  129                 Qatar  Middle east  Global South
  132          Saudi Arabia  Middle east  Global South
  166                 Yemen  Middle east  Global South),
 ('North America',
          Country         Region  Global South
  28       Canada  North America  Global North
  187  MS Zaandam  North America           NaN
  196          US  North America           NaN),
 ('South/Central America',
         Country                 Region  Global South
  114  Nicaragua  South/Central America  Global South),
 ('South/Latin America',
                                Country               Region  Global South
  3                 Antigua and Barbuda  South/Latin America  Global South
  8                           Argentina  South/Latin America  Global South
  13                           Barbados  South/Latin America  Global South
  21                            Bolivia  South/Latin America  Global South
  22                             Brazil  South/Latin America  Global South
  23                            Bahamas  South/Latin America  Global South
  27                             Belize  South/Latin America  Global South
  31                              Chile  South/Latin America  Global South
  34                           Colombia  South/Latin America  Global South
  35                         Costa Rica  South/Latin America  Global South
  36                               Cuba  South/Latin America  Global South
  41                           Dominica  South/Latin America  Global South
  42                 Dominican Republic  South/Latin America  Global South
  44                            Ecuador  South/Latin America  Global South
  55                            Grenada  South/Latin America  Global South
  62                          Guatemala  South/Latin America  Global South
  64                             Guyana  South/Latin America  Global South
  65                           Honduras  South/Latin America  Global South
  67                              Haiti  South/Latin America  Global South
  76                            Jamaica  South/Latin America  Global South
  84              Saint Kitts and Nevis  South/Latin America  Global South
  88                        Saint Lucia  South/Latin America  Global South
  108                            Mexico  South/Latin America  Global South
  120                            Panama  South/Latin America  Global South
  121                              Peru  South/Latin America  Global South
  128                          Paraguay  South/Latin America  Global South
  145                          Suriname  South/Latin America  Global South
  147                       El Salvador  South/Latin America  Global South
  156               Trinidad and Tobago  South/Latin America  Global South
  159                           Uruguay  South/Latin America  Global South
  161  Saint Vincent and the Grenadines  South/Latin America  Global South
  162                         Venezuela  South/Latin America  Global South),
 ('United Kingdom',
                Country          Region Global South
  179  Diamond Princess  United Kingdom          NaN)]

In [18]:
df["Region"].unique()

array(['Europe', 'Middle east', 'Asia & Pacific', 'South/Latin America',
       'Africa', 'Arab States', 'North America', 'South/Central America',
       'United Kingdom'], dtype=object)

In [19]:
out={}
for i in range(0,len(df["Region"].unique())):
    out[df["Region"].unique()[i]]= list(df[(df['Region'] == df["Region"].unique()[i])]["Country"])
out

{'Europe': ['Andorra',
  'Albania',
  'Armenia',
  'Austria',
  'Bosnia and Herzegovina',
  'Belgium',
  'Bulgaria',
  'Belarus',
  'Switzerland',
  'Cyprus',
  'Germany',
  'Denmark',
  'Estonia',
  'Spain',
  'Finland',
  'France',
  'United Kingdom',
  'Georgia',
  'Greece',
  'Croatia',
  'Hungary',
  'Ireland',
  'Iceland',
  'Italy',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Latvia',
  'Monaco',
  'Malta',
  'Netherlands',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Sweden',
  'Slovenia',
  'Slovakia',
  'San Marino',
  'Turkey',
  'Ukraine',
  'Serbia',
  'Montenegro',
  'Czechia',
  'Holy See',
  'Kosovo',
  'Moldova',
  'North Macedonia'],
 'Middle east': ['United Arab Emirates',
  'Egypt',
  'Israel',
  'Iraq',
  'Jordan',
  'Kuwait',
  'Lebanon',
  'Libya',
  'Oman',
  'Qatar',
  'Saudi Arabia',
  'Yemen'],
 'Asia & Pacific': ['Afghanistan',
  'Antarctica',
  'Australia',
  'Azerbaijan',
  'Bangladesh',
  'Bhutan',
  'China',
  'Fiji',
  'Indonesia',
  'India',
  'Japan',
  'Kyrgyzstan',
  'Cambodia',
  'Kiribati',
  'Kazakhstan',
  'Sri Lanka',
  'Marshall Islands',
  'Mongolia',
  'Maldives',
  'Malaysia',
  'Nepal',
  'New Zealand',
  'Papua New Guinea',
  'Philippines',
  'Pakistan',
  'Palau',
  'Solomon Islands',
  'Singapore',
  'Thailand',
  'Tajikistan',
  'Tonga',
  'Timor-Leste',
  'Uzbekistan',
  'Vietnam',
  'Vanuatu',
  'Samoa',
  'Brunei',
  'Burma',
  'Iran',
  'Korea, North',
  'Korea, South',
  'Laos',
  'Micronesia',
  'Russia',
  'Summer Olympics 2020',
  'Syria',
  'Taiwan*',
  'West Bank and Gaza',
  'Winter Olympics 2022'],
 'South/Latin America': ['Antigua and Barbuda',
  'Argentina',
  'Barbados',
  'Bolivia',
  'Brazil',
  'Bahamas',
  'Belize',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Grenada',
  'Guatemala',
  'Guyana',
  'Honduras',
  'Haiti',
  'Jamaica',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Mexico',
  'Panama',
  'Peru',
  'Paraguay',
  'Suriname',
  'El Salvador',
  'Trinidad and Tobago',
  'Uruguay',
  'Saint Vincent and the Grenadines',
  'Venezuela'],
 'Africa': ['Angola',
  'Burkina Faso',
  'Burundi',
  'Benin',
  'Botswana',
  'Central African Republic',
  'Cameroon',
  'Eritrea',
  'Ethiopia',
  'Gabon',
  'Ghana',
  'Gambia',
  'Guinea',
  'Equatorial Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Liberia',
  'Lesotho',
  'Madagascar',
  'Mali',
  'Mauritius',
  'Malawi',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Rwanda',
  'Seychelles',
  'South Sudan',
  'Sierra Leone',
  'Senegal',
  'Sao Tome and Principe',
  'Chad',
  'Togo',
  'Uganda',
  'South Africa',
  'Zambia',
  'Zimbabwe',
  'Cabo Verde',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  "Cote d'Ivoire",
  'Eswatini',
  'Tanzania'],
 'Arab States': ['Bahrain',
  'Djibouti',
  'Algeria',
  'Comoros',
  'Morocco',
  'Mauritania',
  'Sudan',
  'Somalia',
  'Tunisia'],
 'North America': ['Canada', 'MS Zaandam', 'US'],
 'South/Central America': ['Nicaragua'],
 'United Kingdom': ['Diamond Princess']}

In [20]:
dfArray[1][~dfArray[1].Country.isin(df.Country.values)]

Empty DataFrame
Columns: [Country, Confirmed, Deaths]
Index: []

In [21]:
with open("data\\country_regions.json", "w") as outfile:
    json.dump(out, outfile, indent=4, sort_keys=False)